### ISSUE TITLE
他のバンドルとのマッピングと競合する

### ISSUE THREAD

**Issue by qcmatsuoka** [phpmentors-jp/validator-bundle#6]
`app/console cache:clear`実行時に以下のエラーが表示されます。

```
[Symfony\Component\Validator\Exception\ValidatorException]
You cannot set a custom metadata factory after adding custom mappings. You should do either of both.  
```

FOSUserBundleを使用していますが、下記ファイルとマッピングが競合しているようです。
`friendsofsymfony/user-bundle/Resources/config/validation/orm.xml`

対象方法がありましたらご教授ください。

**Comment by iteman** [comment]
`FOSUserBundle`も本バンドルと同じ拡張ポイント（サービス、パラメーター）に変更を加えるものです（詳細は以下のクラスを参照してください）が、本バンドルの方がより根本的な部分に変更を加えますので、`FOSUserBundle`->`PHPMentorsValidatorBundle`の順に`build()`が呼ばれるようにする必要があると思います。`AppKernel::registerBundles()`のバンドルの順番を変更してみてください。

* [validator-bundle/ReplaceFileLoadersPass.php at v1.0.0 · phpmentors-jp/validator-bundle](https://github.com/phpmentors-jp/validator-bundle/blob/v1.0.0/src/DependencyInjection/Compiler/ReplaceFileLoadersPass.php)
* [FOSUserBundle/ValidationPass.php at v1.3.5 · FriendsOfSymfony/FOSUserBundle](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/v1.3.5/DependencyInjection/Compiler/ValidationPass.php)

**Comment by qcmatsuoka** [comment]
@iteman 
丁寧なご回答ありがとうございます。試してみます。

**Comment by qcmatsuoka** [comment]
@iteman 
`AppKernel:registerBundles()`の呼び出し順は`FOSUserBundle`->`PHPMemtorsValidatorBundle`の順になっていました。
参考までに読み込んでいるバンドルは以下の通りです。

```
new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
new Symfony\Bundle\SecurityBundle\SecurityBundle(),
new Symfony\Bundle\TwigBundle\TwigBundle(),
new Symfony\Bundle\MonologBundle\MonologBundle(),
new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
new Symfony\Bundle\AsseticBundle\AsseticBundle(),
new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
new FOS\UserBundle\FOSUserBundle(),
new JMS\AopBundle\JMSAopBundle(),
new JMS\SecurityExtraBundle\JMSSecurityExtraBundle(),
new JMS\DiExtraBundle\JMSDiExtraBundle($this),
new Sp\BowerBundle\SpBowerBundle(),
new Mopa\Bundle\BootstrapBundle\MopaBootstrapBundle(),
new \Knp\Bundle\MenuBundle\KnpMenuBundle(),
new \Knp\Bundle\PaginatorBundle\KnpPaginatorBundle(),
new Sonata\CoreBundle\SonataCoreBundle(),
new Sonata\BlockBundle\SonataBlockBundle(),
new Sonata\AdminBundle\SonataAdminBundle(),
new Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle(),
new FOS\RestBundle\FOSRestBundle(),
new JMS\SerializerBundle\JMSSerializerBundle(),
new FOS\JsRoutingBundle\FOSJsRoutingBundle(),
new \Cypress\AngularNgRoutingBundle\CypressAngularNgRoutingBundle(),
new \Jmikola\JsAssetsHelperBundle\JmikolaJsAssetsHelperBundle(),
new PHPMentors\ValidatorBundle\PHPMentorsValidatorBundle(),
```

バリデーションを扱う`CompilerPass`は`FOSUserBundle` `PHPMemtorsValidatorBundle`の2つのみでした。またSymfony2.5以下で`@validator.builder`が存在しない場合は表記のエラーが起こりませんでした。

大変申し訳ないですがまたアドバイスいただけますでしょうか。

**Comment by iteman** [comment]
本件、`addXmlMappin()`を含むいくつかのメソッドが置換できていなかったのが原因でした。`AppKernel::registerBundles()`のバンドルの順番が`FOSUserBundle`->`PHPMentorsValidatorBundle`であれば、動くようになったと思います。

詳細は 2582642e901d44d124960aa9fd7c21cc308536ba をご覧ください。

**Comment by qcmatsuoka** [comment]
@iteman @hidenorigoto 

ご対応いただき、ありがとうございました。:bow:
新しいバージョンを使わせていただきます！
